[tool.black]
line_length = 100
include = '(aws_replicator|example|tests)/.*\.py$'

[tool.isort]
profile = 'black'
line_length = 100

[tool.flake8]
max-line-length = 100
ignore = 'E501'
exclude = './setup.py,.venv*,dist,build'
