name: Lint GitHub Actions workflows
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
      - '.github/zizmor.yml'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
      - '.github/zizmor.yml'

permissions: {}

jobs:
  lint_workflows:
    name: "Run linters"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Check out repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
        with:
          # Don't integrate with GitHub Advanced Security
          advanced-security: false
