name: Lint GitHub Actions workflows
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
      - '.github/zizmor.yml'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
      - '.github/zizmor.yml'

permissions: {}

jobs:
  lint_workflows:
    name: "Run linters"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          # Don't integrate with GitHub Advanced Security
          advanced-security: false
