name: LocalStack Miniflare Extension Tests

on:
  schedule:
    - cron: '0 2 * * 1-5'
  push:
    paths:
      - miniflare/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/miniflare.yml
      - miniflare/**
  workflow_dispatch:

env:
  LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

jobs:
  tests-miniflare:
    name: Run extension tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: true

      - name: Install LocalStack and extension
        run: |
          cd miniflare

          docker pull localstack/localstack-pro &
          pip install localstack

          make install
          make dist
          localstack extensions -v install file://"$(ls ./dist/localstack_extension_miniflare-*.tar.gz)"

          DEBUG=1 localstack start -d
          localstack wait
          curl http://localhost:4566/_localstack/health
          curl http://localhost:4566/miniflare/user

      - name: Run test
        env:
          CLOUDFLARE_API_TOKEN: test
          CLOUDFLARE_API_BASE_URL: "https://localhost.localstack.cloud:4566/miniflare"
        run: |
          cd miniflare/example
          npm install
          npm run deploy
          curl http://hello.miniflare.localhost.localstack.cloud:4566/test | grep 'Hello World'

      - name: Print LocalStack logs
        if: always()
        run: localstack logs
