name: LocalStack ParadeDB Extension Tests

on:
  schedule:
    - cron: '0 2 * * 1-5'
  push:
    paths:
      - paradedb/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/paradedb.yml
      - paradedb/**
  workflow_dispatch:

env:
  LOCALSTACK_DISABLE_EVENTS: "1"
  LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup LocalStack and extension
        run: |
          cd paradedb

          docker pull localstack/localstack-pro &
          docker pull paradedb/paradedb &
          pip install localstack

          make install
          make lint
          make dist
          localstack extensions -v install file://"$(ls ./dist/localstack_extension_paradedb-*.tar.gz)"

          DEBUG=1 localstack start -d
          localstack wait

      - name: Run integration tests
        run: |
          cd paradedb
          make test

      - name: Print logs
        if: always()
        run: |
          localstack logs
          localstack stop
